server:
  port: 8081
  run_mode: debug

postgres:
  host: postgres-user
  port: 5432
  user: user_user
  password: user_pass
  db_name: user_db
  ssl_mode: disable

kafka:
  brokers:
    - kafka:9092
  group_id: user-service
  topics:
    user_created: user.created.v1

log:
  level: debug
