services:
  # =====================
  # ZOOKEEPER
  # =====================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # =====================
  # KAFKA
  # =====================
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # =====================
  # POSTGRES AUTH
  # =====================
  postgres-auth:
    image: postgres:15
    env_file:
      - ./auth/.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"

  # =====================
  # POSTGRES USER
  # =====================
  postgres-user:
    image: postgres:15
    env_file:
      - ./user/.env
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 5s
      retries: 5
    ports:
      - "5434:5432"

  # =====================
  # POSTGRES IMAGE
  # =====================
  postgres-image:
    image: postgres:15
    env_file:
      - ./image/.env
    volumes:
      - image_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U image_user -d image_db"]
      interval: 5s
      retries: 5
    ports:
      - "5435:5432"

  # =====================
  # AUTH SERVICE
  # =====================
  auth:
    build: ./auth
    depends_on:
      postgres-auth:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - ./auth/.env
    ports:
      - "8080:8080"

  # =====================
  # USER SERVICE
  # =====================
  user:
    build: ./user
    depends_on:
      postgres-user:
        condition: service_healthy
    env_file:
      - ./user/.env
    ports:
      - "8083:8080"

  # =====================
  # IMAGE SERVICE
  # =====================
  image:
    build: ./image
    depends_on:
      postgres-image:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - ./image/.env
    ports:
      - "8081:8080"

  # =====================
  # PROCESSOR SERVICE
  # =====================
  processor:
    build: ./processor
    depends_on:
      postgres-image:
        condition: service_healthy
      kafka:
        condition: service_started
    env_file:
      - ./processor/.env
    ports:
      - "8082:8080"

  # =====================
  # MIGRATE SERVICE
  # =====================
  migrate:
    image: migrate/migrate:4
    depends_on:
      postgres-auth:
        condition: service_healthy
      postgres-user:
        condition: service_healthy
      postgres-image:
        condition: service_healthy
    env_file:
      - ./.env
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./auth/migrations:/migrations/auth
      - ./user/migrations:/migrations/user
      - ./image/migrations:/migrations/image

# =====================
# VOLUMES
# =====================
volumes:
  auth_db_data:
  user_db_data:
  image_db_data:
