version: "3.9"

services:
  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "${AUTH_DB_PORT}:5432"

  postgres-image:
    image: postgres:15
    environment:
      POSTGRES_USER: ${IMAGE_DB_USER}
      POSTGRES_PASSWORD: ${IMAGE_DB_PASS}
      POSTGRES_DB: ${IMAGE_DB_NAME}
    volumes:
      - image_data:/var/lib/postgresql/data
    ports:
      - "${IMAGE_DB_PORT}:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth:
    build: ./auth
    depends_on:
      - postgres-auth
    env_file:
      - ./auth/.env
    ports:
      - "8081:8080"

  image-api:
    build: ./image-api
    depends_on:
      - postgres-image
      - kafka
    env_file:
      - ./image-api/.env
    ports:
      - "8080:8080"

  processor:
    build: ./processor
    depends_on:
      - kafka
    env_file:
      - ./processor/.env

volumes:
  auth_data:
  image_data:
