# Stage 1: Builder
FROM golang:1.25-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /app/bin/app cmd/main.go

# Stage 2: Runtime
FROM alpine:latest

RUN apk add --no-cache tini

WORKDIR /app
COPY --from=builder /app/bin/app .
EXPOSE 8080
CMD ["./app"]
